### ISSUE TITLE
&copy; doesn't work

### ISSUE THREAD

**Issue by brandonros** [hyperapp/html#13]

**Comment by jorgebucaran** [comment]
I &copy;. 😉 

I think we've discussed this before, but I can't find the link. I'll keep you posted.

/cc @frenzzy @Swizz @lukejacksonn

**Comment by jorgebucaran** [comment]
@brandonros We don't support HTML [entities](https://developer.mozilla.org/en-US/docs/Glossary/Entity), but you can insert them within literal text **in JSX** (since they are computed at compilation time).

```jsx
<div>First &middot; Second</div>
```
> `First &middot; Second` →  **First · Second**

If you want to display an HTML entity within **dynamic content** that won't work. So, neither this package or the built-in `h` function handle entities.

The most obvious way to work around this is by using the Unicode character itself.

```js
return div({}, "2018 ©")
```

Use the unicode codepoint.

```js
h1("h1", {}, "First \u00A9 Second")
```

Or use String.fromCharCode.
```js
h1("h1", {}, "First " + String.fromCharCode(169) + " Second")
```

**Comment by jorgebucaran** [comment]
Sounds like this could make it to the docs somehow. But that belongs to hyperapp/hyperapp, not here.

**Comment by Swizz** [comment]
Here is the previous issue : #7

**Comment by frenzzy** [comment]
It because the character `&` is not safe and it automatically escaped by `&amp;`.

Your `&copy;` become `&amp;copy;` during rendering ([`Node.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) and [`Node.nodeValue`](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeValue)) and correspondingly displayed on the page as `&copy;` instead of `©`.

The recommended way is to use utf-8 characters and `<meta charset="utf-8"/>` as a first line in your html. Also you can use unsafe way: `<div innherHTML="&copy;" />` (not recommended).

Read more: https://www.w3.org/International/questions/qa-escapes
